apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-kafka-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "512Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/run/docker.sock"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-kafka-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-kafka-app
  labels:
    test-kafka-deployment: kaviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      test-kafka-pod: kaviewer
  template:
    metadata:
      labels:
        test-kafka-pod: kaviewer
    spec:
      containers:
        - name: test-kafka
          image: landoop/fast-data-dev
          ports:
            - containerPort: 2181
            - containerPort: 3030
            - containerPort: 8081
            - containerPort: 8082
            - containerPort: 8083
            - containerPort: 9092
          env:
            - name: ADV_HOST
              value: "localhost"
            - name: SAMPLEDATA
              value: "0"
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: test-kafka-pv-storage
      volumes:
        - name: test-kafka-pv-storage
          persistentVolumeClaim:
            claimName: test-kafka-pvc