#Env
#kaviewer.config.filepath=/kaviewer/example-config.yaml
kaviewer:
  mode: FULL
  toggle:
    topic:
      delete: false
    consumer:
      read: false
    cluster:
      create: true
  connections:
    - cluster: newCluster
      bootstrapServers: localhost:9092
    - cluster: newCluster2
      bootstrapServers: connection:9092
      jaasConfig: org.apache.kafka.common.security.plain.PlainLoginModule ...;
      securityProtocol: SASL_SSL
      saslMechanism: PLAIN
