#Env
#kaviewer.config.filepath=/kaviewer/example-config.yaml
#kaviewer_mode=LITE
kaviewer:
  mode: FULL
  toggle:
    topic:
      delete: true
#    consumer:
#      read: false
#    cluster:
#      create: true
#  kafka:
#    cluster: newCluster
#    bootstrapServers: localhost:9092
