#Env
#kaviewer.config.filepath=/kaviewer/example-config.yaml
kaviewer:
  mode: FULL
  toggle:
    topic:
      delete: true
    consumer:
      read: false
    cluster:
      create: true
  connections:
    - cluster: newCluster
      bootstrapServers: localhost:9092
    - cluster: newCluster2
      bootstrapServers: kafka_service:9093
