{{- if .Values.config_secret_enable -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-config-secret
  labels:
    {{- include "kaviewer.labels" . | nindent 4 }}
type: Opaque
stringData:
    {{- range $key, $value:= .Values.set_up_kafka_env }}
     {{$key}}: {{$value | quote}}
    {{- end }}
{{- end}}
