{{- if .Values.config_configmap_enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}-config-configmap
  labels:
    {{- include "kaviewer.labels" . | nindent 4 }}
data:
  kaviewer-config.yaml: |
    kaviewer:
      mode: FULL
      toggle:
         topic:
          delete: false
         cluster:
          delete: false
{{- end}}
