apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-apps
  labels:
    {{- include "kaviewer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kaviewer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "kaviewer.commonAnnotations" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kaviewer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.config_secret_enable }}
          envFrom:
            - secretRef:
                  name: {{ .Chart.Name }}-config-secret
          {{- else}}
            {{- range $key, $value:= .Values.set_up_kafka_env}}
            - name: {{$key}}
              value: {{$value | quote}}
            {{- end}}
          {{- end }}
          ports:
            - name: app
              containerPort: 9394
              protocol: TCP
            - name: actuator
              containerPort: 10086
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /monitor/health
              port: {{.Values.service.actuator.port}}
            initialDelaySeconds: 180
            failureThreshold: 36
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /monitor/health
              port: {{.Values.service.actuator.port}}
            failureThreshold: 36
            periodSeconds: 10

  {{- if .Values.resources.enabled -}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
