apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaviewer.fullname" . }}-{{ .Release.Name }}-service
  labels:
    {{- include "kaviewer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.app.port }}
      name: app
      targetPort: {{ .Values.service.app.targetPort }}
      protocol: TCP
    - port: {{ .Values.service.actuator.port }}
      name: actuator
      targetPort: {{ .Values.service.actuator.targetPort }}
      protocol: TCP
  selector:
    {{- include "kaviewer.selectorLabels" . | nindent 4 }}
