spring:
  application:
    name: KaViewer
management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: info,health,contexts
      cors:
        allowed-origin-patterns: '*'
    # must disable jmx endpoint for JmxEndpoint/InstanceAlreadyExistsException exception
    jmx:
      exposure:
        exclude: '*'
  server:
    port: 10086

kaviewer:
  version: @project.version@