server:
  port: 9394

spring:
  application:
    name: KaViewer-Rest
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
springfox:
  documentation:
    swagger-ui:
      enabled: true