spring:
  application:
    name: KaViewer
management:
  #  endpoint:
  #    health:
  #      show-details: always
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: info,health,contexts
      cors:
        allowed-origin-patterns: '*'
  server:
    port: 10086

kaviewer:
  version: @project.version@