spring:
  application:
    name: KaViewer
  jmx:
    unique-names: true
management:
  #  endpoint:
  #    health:
  #      show-details: always
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: info,health
      cors:
        allowed-origin-patterns: '*'
    # must disable jmx endpoint for JmxEndpoint exception
    jmx:
      exposure:
        exclude: '*'
  server:
    port: 10086