spring:
  application:
    name: KaViewer
management:
  endpoints:
    web:
      base-path: ${kaviewer.app.monitor-path:/monitor}
      exposure:
        include: info,health,contexts
      cors:
        allowed-origin-patterns: '*'
    # must disable jmx endpoint for JmxEndpoint/InstanceAlreadyExistsException exception
    # https://github.com/spring-projects/spring-boot/issues/31718
    jmx:
      exposure:
        exclude: '*'
  server:
    port: ${kaviewer.app.monitor-port:10086}

kaviewer:
  version: @project.version@