server:
  port: 9394

spring:
  application:
    name: KaViewer-Rest
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
springdoc:
  packages-to-scan: "com.koy.kaviewer.web.api"
  paths-to-match: /api/**
  swagger-ui:
    csrf:
      enabled: true
    path: /docs/swagger-ui.html
    defaultModelsExpandDepth: -1
