version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka-service:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-service:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENERS: INTERNAL://kafka-service:9093,EXTERNAL://kafka-service:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka:/var/run/docker.sock
    depends_on:
      - zookeeper

  kaviewer:
    image: kooooooy/kaviewer:0.0.1-alpha
    ports:
      - 9394:9394
    environment:
      KAVIEWER.TOGGLE.TOPIC.DELETE:
      KAVIEWER.KAFKA.CLUSTER:
      KAVIEWER.KAFKA.BOOTSTRAPSERVERS:

    depends_on:
      - kafka-service
    container_name: kaviewer

volumes:
  kafka:

