name: KaViewer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true --file pom.xml

      - name: Copy file to docker
        run: mkdir -p docker/app/target/ && mv app/target/*.jar docker/app/target/

      - name: Run Docker Env for BDD
        run: docker-compose -f docker/docker-compose-bdd.yaml up -d

      - name: Run BDD test
        run: mvn test -DargLine="-Dkarate.env=e2e"

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          files: /home/runner/work/KaViewer/KaViewer/app/target/karate-reports/karate-summary.html

      - name: Upload BDD test report
        uses: actions/upload-artifact@v3
        with:
          name: bdd-test-report-${{ github.event.pull_request.head.sha }}
          path: app/target/karate-reports/
          retention-days: 3
